[package]
name = "syncrim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["mips"]

[dependencies]
clap = { version = "4.3.10", features = ["derive"] }
petgraph = "0.6.3"
rfd = "0.11.4"
serde = { version = "1.0.166", features = ["rc"] }
serde_derive = "1.0.166"
serde_json = "1.0.99"
typetag = "0.2.8"

vizia = { git = "https://github.com/vizia/vizia.git" }
# vizia = { path = "../vizia" } # using local vizia dependency

[profile.dev]
debug = 1 # faster build, still allows for stack back trace

[profile.release]
incremental = true
debug = 1 # faster build, still allows for stack back trace
