[package]
name = "syncrim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["mips"]

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
petgraph = "0.6.3"
serde = { version = "1.0.163", features = ["rc"] }
serde_derive = "1.0.163"
serde_json = "1.0.96"
typetag = "0.2.8"

# vizia = { git = "https://github.com/vizia/vizia.git", features = ["serde"] }
vizia = { git = "https://github.com/perlindgren/vizia.git", branch = "icons-update", features = [
    "serde",
] }
# vizia = { path = "../vizia", features = ["serde"] }

