[package]
name = "syncrim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["mips"]

[dependencies]
clap = { version = "4.3.10", features = ["derive"] }
petgraph = "0.6.3"
rfd = "0.11.4"
serde = { version = "1.0.164", features = ["rc"] }
serde_derive = "1.0.164"
serde_json = "1.0.99"
typetag = "0.2.8"

vizia = { git = "https://github.com/vizia/vizia.git" }
# vizia = { git = "https://github.com/perlindgren/vizia.git", branch = "icons-update", features = ["serde"] }
# vizia = { path = "../vizia", features = ["serde"] }

[profile.dev]
debug = 0

[profile.release]
incremental = true
debug = 0
