[package]
name = "mips"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syncrim = { path = "../" }
serde = "1.0.160"
serde_derive = "1.0.160"
typetag = "0.2.8"
serde_json = "1.0.96"
