[package]
name = "riscv_basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = {version = "0.10.1", features=["critical-section-single-hart"]}
volatile-register = "0.2.1"
critical-section = "1.1.2"
clic = {path = "../../../clic/", features=["rt"]}
riscv-rt = "0.11.0"
syncrim-clic-rt = {path = "../../../syncrim-clic-rt"}
rtic = {path = "../../../rtic/rtic/", features =["riscv-clic-backend"]}

[workspace]
