name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install librust-atk-dev librust-gdk-dev
    - uses: rui314/setup-mold@v1
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v3
      with:
        path: target/debug/syncrim
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install librust-atk-dev librust-gdk-dev
      - uses: rui314/setup-mold@v1
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
