name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install librust-atk-dev librust-gdk-dev
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features --features gui-vizia
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features --features gui-egui
      - name: Run tests
        run: cargo test --workspace --no-default-features --features components --verbose
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: rustfmt
        run: cargo fmt --all -- --check